version: '3'

services:
  dev-db:
    image: mysql:8.0
    container_name: dev-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
  prod-db:
    image: mysql:8.0
    container_name: prod-db
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root