name: Database Migration Tests with Flyway

on:
  push:
    branches:
    - 'main'
    paths:
      - 'db/migration/**'
  pull_request:
    paths:
    - 'db/migration/**'
  workflow_dispatch: {}

jobs:
  test-migrations:
    name: Test flyway migration scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v2
      - name: Test migrations on Flyway Hub
        uses: red-gate/flyway-hub-migration-test@v4
        with:
          projectName: versioning-db
          engine: mysql-8
          migrationDirs: db/migration  
env:
  FLYWAYHUB_ACCESS_TOKEN: ${{ secrets.FLYWAY_HUB_ACCESS_TOKEN }}
